### ISSUE TITLE
Identify All Necessary Skims

### ISSUE THREAD

**Issue by danielsclint** [wsp-sag/client_arc_activitysim#1]
Review the existing UECs, and develop a comprehensive list of the necessary skims needed to run the ARC CT-RAMP model.

**Comment by sidharthanr** [comment]
@danielsclint, I have the list of necessary skims in the skim manifest format. Should I add a script folder and add it there? Do you want me to make changes to the master branch or create a new branch?

**Comment by danielsclint** [comment]
For now, put in a new folder. (We may change it later, but its good for now.) You'll need to do it on a new branch and issue a pull request to put in the master branch.

**Comment by sidharthanr** [comment]
Okay, will do.
