### ISSUE TITLE
shortWalkOrig Value: Anything Other Than 1?

### ISSUE THREAD

**Issue by danielsclint** [wsp-sag/client_arc_activitysim#14]
@sidharthanr: I’ve been working through converting the work and school destination choice UECs to ActivitySim for ARC, and I have a question regarding the ‘shortWalkOrig’ value in the Workplace location UEC. If I’m reading this UEC correctly (which I may not), it looks like shortWalkOrig is always set to a value of 1 which renders it pretty useless. I assume I’m not reading it correctly, but I’m not sure what this value is supposed to be. I’ve looked through the raw ARC Java source code, and I don’t see any references to it in the ARCHouseholdDataManager or ARCDestChoiceDMU. In the ARCHouseholdDataManager there is a property called hhWalkSubZone, but the comments suggest it has been removed from the model flow setting the value to 0. Can you shed any light on whether this shortWalkOrig ever takes on any value besides 1?

I grabbed the UEC from here: https://github.com/wsp-sag/ARC_Model/blob/master/ctrampModels/DestinationChoice.xls

**Comment by sidharthanr** [comment]
@danielsclint, you are reading the UEC correctly. The shortWalkOrigvariable is hard coded to 1 in UEC. Maybe at one point it was used and that segmentation was discarded later. Note that ARC CTRAMP code is coming from two repos. The [arc](https://github.com/wsp-sag/arc) and [ctramp](https://github.com/wsp-sag/ctramp) repo. So some methods are called from the ctramp repo also. As far as work location is concerned shortWalkOrig is definitely set to 1 in the UEC.

**Comment by danielsclint** [comment]
Thanks.
