### ISSUE TITLE
Identify Minimum Inputs Necessary to Run ARC Accessibilities

### ISSUE THREAD

**Issue by danielsclint** [wsp-sag/client_arc_activitysim#3]
Using the [ARC Accessibility Logsum class](https://github.com/wsp-sag/arc/blob/master/src/java/com/pb/arc/tourBased/ArcAccessibilityLogsums.java) identify the minimum necessary land use, person, household, and skim inputs needed to run and calculate ARC transit accessibilities.

The ARC [accessibility batch script](https://github.com/wsp-sag/ARC_Model/blob/master/config/RunAccessibility.bat) controls the process, and it can be run in isolation.

**Comment by sidharthanr** [comment]
@danielsclint, do we use the accessibility produced by this script in the current model flow? In the Cube script I see the accessibility file created directly by the Cube script.
https://github.com/wsp-sag/ARC_Model/blob/1fee32b63ca9faf6f30e3ef3d3c4fe4d2bf76930/ARC_ABM_3-12-18.s#L6715

**Comment by danielsclint** [comment]
Okay, that is good to know. Can you confirm that the [Run_Accessibilities.bat](https://github.com/wsp-sag/ARC_Model/blob/master/config/RunAccessibility.bat) is not used. 

Regardless of whether the accessibilities are created in Cube or Java, we should move it inside the ActivitySim container. In the Cube script, I don't see anything downstream in the script that is using the accessibilities.csv that is generated. My sense is the ActivitySim implementation will be faster than the loops in Cube or Java.

**Comment by sidharthanr** [comment]
I will check with Jonathan about Run_Accessibilities.bat. 
The accessibilities.csv is actually used by CT-RAMP, specified in the property file (created on the fly by Cube)
https://github.com/wsp-sag/ARC_Model/blob/1fee32b63ca9faf6f30e3ef3d3c4fe4d2bf76930/ARC_ABM_3-12-18.s#L8443
CDAP and AO model UEC file uses accessibilities.csv as an input

**Comment by danielsclint** [comment]
Based on the response from Jonathan, I recommend we convert the Cube Accessibilities script to the ActivitySim. It will give us good practice on an easier problem set, and it will probably be much faster than the Cube script (although I'm guessing were talking seconds and not minutes in this case).
