### ISSUE TITLE
Add Accessibility Inputs to HDF5

### ISSUE THREAD

**Issue by danielsclint** [wsp-sag/client_arc_activitysim#5]
Using the findings from #3, create the necessary tables and add them to the project [HDF5 input file](data/arc_asim.h5).

The current ARC inputs are [here](https://github.com/wsp-sag/ARC_Model/tree/master/Inputs). For future compatibility, we should write a script that uses these inputs.

**Comment by chryssac** [comment]
accessibility inputs were added to HDF5 file
